PROGRAM PROG38;
USES WINCRT;

PROCEDURE TAMPIL1;
BEGIN
     GOTOXY(35,11);WRITE('STMIK WIDYA PRATAMA PEKALONGAN');
END;

PROCEDURE TAMPIL2;
BEGIN
     GOTOXY(40,12);WRITE('JL.PATRIOT NO 25');
END;

BEGIN
     CLRSCR;
     TAMPIL1;
     TAMPIL2;
END.